# Generated by Django 2.2.17 on 2020-11-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_auto_20201117_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_list',
            old_name='bought',
            new_name='complete',
        ),
    ]
